// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230903122127_default-types")]
    partial class defaulttypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Character.BaseCharacter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("contentCharacters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "basic",
                            typeId = 1
                        },
                        new
                        {
                            id = 2,
                            name = "grass",
                            typeId = 2
                        },
                        new
                        {
                            id = 3,
                            name = "water",
                            typeId = 3
                        },
                        new
                        {
                            id = 4,
                            name = "fire",
                            typeId = 4
                        });
                });

            modelBuilder.Entity("Game_API.Models.Content.ContentCharacterType", b =>
                {
                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strongAgainst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weakAgainst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("type");

                    b.ToTable("contentCharacterTypes");

                    b.HasData(
                        new
                        {
                            type = 0,
                            name = "Unknown",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 1,
                            name = "Normale",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 2,
                            name = "Grass",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 3,
                            name = "Fire",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 4,
                            name = "Water",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 5,
                            name = "Electric",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 6,
                            name = "Rock",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 7,
                            name = "Steel",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 8,
                            name = "Ground",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 9,
                            name = "Fairy",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 10,
                            name = "Dark",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 11,
                            name = "Ghost",
                            strongAgainst = "",
                            weakAgainst = ""
                        },
                        new
                        {
                            type = 12,
                            name = "Fighting",
                            strongAgainst = "",
                            weakAgainst = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
