// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230903112755_types")]
    partial class types
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Character.BaseCharacter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("contentCharacters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "basic",
                            typeId = 1
                        },
                        new
                        {
                            id = 2,
                            name = "grass",
                            typeId = 2
                        },
                        new
                        {
                            id = 3,
                            name = "water",
                            typeId = 3
                        },
                        new
                        {
                            id = 4,
                            name = "fire",
                            typeId = 4
                        });
                });

            modelBuilder.Entity("Game_API.Models.Content.ContentCharacterType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strongAgainst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("weakAgainst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("contentCharacterTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            strongAgainst = "",
                            type = 0,
                            weakAgainst = ""
                        },
                        new
                        {
                            id = 2,
                            strongAgainst = "4",
                            type = 0,
                            weakAgainst = "3"
                        },
                        new
                        {
                            id = 3,
                            strongAgainst = "3",
                            type = 0,
                            weakAgainst = "2"
                        },
                        new
                        {
                            id = 4,
                            strongAgainst = "2",
                            type = 0,
                            weakAgainst = "4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
